return {
  -- "folke/flash.nvim",
  -- -- event = "VeryLazy",
  -- ---@type Flash.Config
  -- opts = {
  --   modes = {
  --     search = {
  --       enabled = true,
  --     },
  --     char = {
  --       enabled = true,
  --       jump_labels = true,
  --     },
  --   },
  -- },
  --   -- stylua: ignore
  --   keys = {
  --     { "f", mode = { "n", "x", "o" }, function() require("flash").jump({mode="char"}) end, desc = "Flash Char Jump" },
  --     { "F", mode = { "n", "x", "o" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
  --     { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
  --   },
}
